import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <BrowserRouter>
      <App />
    </BrowserRouter>
  </React.StrictMode>
);

// Register the Workbox service worker generated by vite-plugin-pwa.
// autoUpdate means users silently get the latest version on next page load.
registerSW({
  onNeedRefresh() {
    // Could show a toast: "New version available – refresh to update"
    console.info('[NammaCity SW] New version available.');
  },
  onOfflineReady() {
    console.info('[NammaCity SW] App ready to work offline ✓');
  },
});
